# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('css_class', models.CharField(blank=True, choices=[('event-warning', 'Credit'), ('event-info', 'Borrowing'), ('event-success', 'Repay'), ('event-inverse', 'Interest'), ('event-special', 'Special'), ('event-important', 'Important')], max_length=20, verbose_name='CSS Class')),
                ('start', models.DateTimeField(verbose_name='Start Date')),
                ('cre_date', models.DateTimeField(auto_now_add=True)),
                ('upd_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
